name: onMainRelease

on:
  push:
    tags:
      - "v*"

jobs:
  check_if_main_branch:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.decide.outputs.proceed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetchssss alls history for all branches and tags
      - name: Determine if tag is on main branch
        id: decide
        run: |
          BRANCH_NAME=$(git branch -r --contains ${{ github.sha }} | grep 'origin/main' | sed 's/origin\///' | xargs)

          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "proceed=false" >> $GITHUB_OUTPUT
          fi
